-- SUPABASE SCHEMA FOR ADAPTIVE E-LEARNING PLATFORM

-- 1. Users Table
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT auth.uid(),
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT DEFAULT 'kid' CHECK (role IN ('kid', 'parent', 'teacher')),
    level TEXT DEFAULT 'easy' CHECK (level IN ('easy', 'medium', 'hard')),
    points INTEGER DEFAULT 0,
    stars INTEGER DEFAULT 0,
    badges TEXT[] DEFAULT '{}',
    reset_otp TEXT,
    reset_otp_expiry TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. Quiz Results Table
CREATE TABLE quiz_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    lesson_id TEXT, -- Can be UUID if lessons move to DB, or string for content bank topics
    lesson_title TEXT,
    subject TEXT,
    score INTEGER NOT NULL,
    total_questions INTEGER NOT NULL,
    level TEXT,
    passed BOOLEAN,
    stars_earned INTEGER DEFAULT 0,
    average_response_time FLOAT,
    emotion TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Study Materials Table (Teacher Uploads)
CREATE TABLE study_materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject TEXT NOT NULL,
    topic TEXT NOT NULL,
    difficulty TEXT NOT NULL,
    content_type TEXT NOT NULL,
    youtube_url TEXT NOT NULL,
    description TEXT,
    created_by TEXT, -- Teacher ID or Name
    status TEXT DEFAULT 'active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. Quizzes Table (Teacher Created)
CREATE TABLE quizzes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject TEXT NOT NULL,
    topic TEXT NOT NULL,
    difficulty TEXT NOT NULL,
    questions JSONB NOT NULL, -- Array of question objects
    created_by TEXT,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. Learning Logs Table (Adaptive History)
CREATE TABLE learning_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    subject TEXT,
    topic TEXT,
    quiz_score INTEGER,
    emotion TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- RLS (Row Level Security) - Optional but recommended for Supabase
-- For now, we will use the Service Role Key for backend operations, 
-- but you can enable RLS and add policies later.
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE quiz_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE quizzes ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_logs ENABLE ROW LEVEL SECURITY;
